name: Deploy to AWS S3

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: "Select Deployment Environment"
        options:
          - develop
          - acceptance
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Configure AWS Credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          role-to-assume: ${{secrets.AWS_ROLE_ARN}}
          aws-region: eu-north-1

      - name: Test AWS Credentials
        run: aws sts get-caller-identity

      # - name: Configure AWS OIDC Authentication
      #   uses: aws-actions/configure-aws-credentials@v2
      #   with:
      #     role-to-assume: arn:aws:iam::327816341313:role/github-action-s3-role
      #     aws-region: eu-north-1

      # - name: Deploy to S3
      #   run: |
      #     aws s3 sync ./ s3://${{ vars.S3_BUCKET }} --delete
